<p>Tier 5 talents offer a choice between 3 abilities that help you protect raid members.</p>
<ul>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_shieldbreak.png" alt="Mass Spell Reflection Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=114028" rel="nofollow">Mass Spell Reflection</a></span> reflects the next spell cast on you and on all party and raid members within 20 yards for 5 seconds. It has a 1-minute cooldown and, unlike its single-target counter-part (<span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_shieldreflection.png" alt="Spell Reflection Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=23920" rel="nofollow">Spell Reflection</a></span>),it does not require that you have a shield equipped.</li>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_safeguard.png" alt="Safeguard Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=114029" rel="nofollow">Safeguard</a></span> is an improvement over <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_victoryrush.png" alt="Intervene Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=3411" rel="nofollow">Intervene</a></span>, which it replaces. It allows you to intercept the next melee or ranged attack (not spells) made against the targeted raid member (the attack is done to you instead), and it reduces the damage they take by 20% for 6 seconds. In the process of doing so, you charge the targeted raid member, also removing any movement-impairing effects that may have been on you. Safeguard has a 30-second cooldown.</li>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_vigilance.png" alt="Vigilance Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=114030" rel="nofollow">Vigilance</a></span> reduces the damage taken by the target by 30% for 12seconds. While Vigilance is active, your <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/spell_nature_reincarnation.png" alt="Taunt Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=355" rel="nofollow">Taunt</a></span> has no cooldown, andTaunt's cooldown is reset when Vigilance is cast. Vigilance has a 2-minute cooldown.</li>
</ul>
<p>While the choice here depends somewhat on what the encounter mechanics are, <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_vigilance.png" alt="Vigilance Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=114030" rel="nofollow">Vigilance</a></span> is the best choice in most situations. The talent is exceptional because not only does it essentially provide an extra defensive cooldown to the other tank (or another raid member), but the fact that it effectively removes the cooldown of <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/spell_nature_reincarnation.png" alt="Taunt Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=355" rel="nofollow">Taunt</a></span> makes it great for picking up multiple targets. Given the fact that using Taunt on a target of which you already have aggro causes you to generate an additional 200% threat against that target for 3 seconds, this can even be used to boost your threat generation (although you will need to be mindful of the diminishing returns of Taunt).</p>
<p><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_safeguard.png" alt="Safeguard Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=114029" rel="nofollow">Safeguard</a></span> is also quite good, but beware of the fact that it causes you to intercept the next attack made against the target (you take the damage from the attack), which may not always be desirable.</p>
<p><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_shieldbreak.png" alt="Mass Spell Reflection Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=114028" rel="nofollow">Mass Spell Reflection</a></span> is useful in the event that there are important spells that can be reflected. Since most boss abilities can not be reflected(and those that can be generally do not pose problems), this talent will not be used very much.</p>
