<p>As a Protection Warrior, Major Glyphs offer you various damage (and threat) improvements, but they do very little for your survivability.</p>
<p>The following glyphs improve your damage and threat.</p>
<ul>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_glyph_majorwarrior.png" alt="Glyph of Heavy Repercussions Icon"> <a class="glyph" href="http://mop-shoot.tauri.hu/?item=43415" rel="nofollow">Glyph of Heavy Repercussions</a></span> causes your <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_shield_05.png" alt="Shield Slam Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=23922" rel="nofollow">Shield Slam</a></span> to deal an extra 50% damage while <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_defend.png" alt="Shield Block Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=2565" rel="nofollow">Shield Block</a></span> is active.</li>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_glyph_majorwarrior.png" alt="Glyph of Hold the Line Icon"> <a class="glyph" href="http://mop-shoot.tauri.hu/?item=43424" rel="nofollow">Glyph of Hold the Line</a></span> increases the damage of your next <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_revenge.png" alt="Revenge Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=6572" rel="nofollow">Revenge</a></span>, following a successful parry, by 50%.</li>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_glyph_majorwarrior.png" alt="Glyph of Incite Icon"> <a class="glyph" href="http://mop-shoot.tauri.hu/?item=83096" rel="nofollow">Glyph of Incite</a></span> causes your <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_warcry.png" alt="Demoralizing Shout Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=1160" rel="nofollow">Demoralizing Shout</a></span> to make your next 3 <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_rogue_ambush.png" alt="Heroic Strike Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=78" rel="nofollow">Heroic Strike</a></span> or <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_cleave.png" alt="Cleave Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=845" rel="nofollow">Cleave</a></span> casts free of cost.</li>
</ul>
<p>Several other glyphs can, in some situations, increase your DPS and threat.</p>
<ul>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_glyph_majorwarrior.png" alt="Glyph of Death From Above Icon"> <a class="glyph" href="http://mop-shoot.tauri.hu/?item=45792" rel="nofollow">Glyph of Death From Above</a></span> reduces the cooldown of your <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_heroicleap.png" alt="Heroic Leap Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=6544" rel="nofollow">Heroic Leap</a></span>by 15 seconds. If you have a chance to make use of HeroicLeap more often than its standard cooldown allows for, then this glyph is a solid option. That said, this glyph should pretty much always betaken.</li>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_glyph_majorwarrior.png" alt="Glyph of Unending Rage Icon"> <a class="glyph" href="http://mop-shoot.tauri.hu/?item=43399" rel="nofollow">Glyph of Unending Rage</a></span> increases your rage pool by 20, giving you a maximum rage amount of 120. This glyph will probably be beneficial in every possible scenario, making it much easier for you to manage your rage. Additionally, it allows you to pool up rage (even if only slightly), which you can then use in a time of need.</li>
</ul>
<p><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_glyph_majorwarrior.png" alt="Glyph of Shield Wall Icon"> <a class="glyph" href="http://mop-shoot.tauri.hu/?item=45797" rel="nofollow">Glyph of Shield Wall</a></span> causes <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_shieldwall.png" alt="Shield Wall Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=871" rel="nofollow">Shield Wall</a></span> to reduce an additional 20% damage taken, at the expense of increasing its cooldown by 2 minutes. While this glyph is not something you would normally use, it can be very beneficial in some situations.</p>
<p>Finally, <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/inv_glyph_majorwarrior.png" alt="Glyph of Enraged Speed Icon"> <a class="glyph" href="http://mop-shoot.tauri.hu/?item=43413" rel="nofollow">Glyph of Enraged Speed</a></span> increases your movement speed by 20% while you are enraged.</p>
