<p>Tier 4 offers a choice between 3 important, damage-dealing abilities.</p>
<ul>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_bladestorm.png" alt="Bladestorm Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=46924" rel="nofollow">Bladestorm</a></span> deals damage to all enemies within 8 yards for 6seconds. While Bladestorm is active, you cannot perform any actions except for using your shouts. You are, however, immune to disarms, and movement-impairing and loss of control effects, and you continue to dodge, parry and block attacks.It has a 1-minute cooldown.</li>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_shockwave.png" alt="Shockwave Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=46968" rel="nofollow">Shockwave</a></span> deals damage to and stuns all enemies in a 10-yard cone in front of you for 4 seconds. It has a 40-second cooldown, but if it hits 3or more targets, the cooldown is reduced to 20 seconds.</li>
    <li><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_dragonroar.png" alt="Dragon Roar Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=118000" rel="nofollow">Dragon Roar</a></span> deals damage to all enemies within 8 yards, knocking them back and knocking them down for 0.50 seconds. It ignores armor and it is always a critical strike. It has a 1-minute cooldown. Unlike most other AoE attacks, the damage of Dragon Roar drops sharply as more targets are hit by it,so for single target situations, it is desirable to only hit your main target with it.</li>
</ul>
<p>Only <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_shockwave.png" alt="Shockwave Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=46968" rel="nofollow">Shockwave</a></span> provides you with any kind of survivability increase(assuming that you are facing stunnable adds), so if this is the case, and you are interested in gaining a small amount of survivability, this is a good choice.</p>
<p>In terms of DPS contribution, <span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_dragonroar.png" alt="Dragon Roar Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=118000" rel="nofollow">Dragon Roar</a></span> is ideal against a single target.</p>
<p><span class="spell_icon_span"><img class="spell_icon" src="http://mop-static.tauri.hu/images/icons/medium/ability_warrior_bladestorm.png" alt="Bladestorm Icon"> <a class="spell" href="http://mop-shoot.tauri.hu/?spell=46924" rel="nofollow">Bladestorm</a></span> is ideal for moments when you want to avoid being the victim of movement-impairing effects or effects that cause loss of control of your character, but its damage is quite a bit lower than the other two.</p>
